stages:
  - unittest
  - build
  
unittest:
  stage: unittest
  image: node:16
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm run test
    - echo "Test successfully"

build:
  stage: build
  image: node:16
  script:
    - echo "Start building App"
    - npm install
    - echo "$ENV_VAR_DEV" > .env
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  except:
    - prod