import i18next from 'i18next';
import ar from './navigation-i18n/ar';
import en from './navigation-i18n/en';
import tr from './navigation-i18n/tr';
import authRoles from 'src/app/auth/authRoles';

i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('tr', 'navigation', tr);
i18next.addResourceBundle('ar', 'navigation', ar);

const navigationConfig = [
      {
        id: 'dashboards.home',
        title: 'Home',
        type: 'item',
        icon: 'heroicons-outline:home',
        url: '/home',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.cpd',
        title: 'CPD',
        type: 'item',
        icon: 'heroicons-outline:academic-cap',
        url: '/cpd',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.learnerOverview',
        title: 'Learner Overview',
        type: 'item',
        icon: 'heroicons-outline:chart-pie',
        url: '/learnerOverview',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.caseload',
        title: 'Caseload',
        type: 'item',
        icon: 'heroicons-outline:chart-square-bar',
        url: '/caseload',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.reports',
        title: 'Reports',
        type: 'item',
        icon: 'heroicons-outline:document-report',
        url: '/reports',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.resources',
        title: 'Resources',
        type: 'item',
        icon: 'heroicons-outline:library',
        url: '/resources',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.forum',
        title: 'Forum',
        type: 'item',
        icon: 'heroicons-outline:users',
        url: '/forum',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.calendar',
        title: 'Calendar',
        type: 'item',
        icon: 'heroicons-outline:calendar',
        url: '/calendar',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.support',
        title: 'Support',
        type: 'item',
        icon: 'heroicons-outline:hand',
        url: '/support',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.proposeYourInnovations',
        title: 'Propose Your Innovations',
        type: 'item',
        icon: 'feather:target',
        url: '/proposeYourInnovations',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.skillsScan',
        title: 'Skills Scan',
        type: 'item',
        icon: 'heroicons-outline:qrcode',
        url: '/skillsScan',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.createAssignment',
        title: 'Create Assignment',
        type: 'item',
        icon: 'heroicons-outline:pencil-alt',
        url: '/createAssignment',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.portfolio',
        title: 'Portfolio',
        type: 'item',
        icon: 'heroicons-outline:user-circle',
        url: '/portfolio',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.offTheJob',
        title: 'Off The Job',
        type: 'item',
        icon: 'material-outline:home_work',
        url: '/offTheJob',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.trainerRiskRating',
        title: 'Trainer Risk Rating',
        type: 'item',
        icon: 'material-outline:thumbs_up_down',
        url: '/trainerRiskRating',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.samplingPlan',
        title: 'Sampling Plan',
        type: 'item',
        icon: 'heroicons-outline:puzzle',
        url: '/samplingPlan',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.samplingPlanAllocation',
        title: 'Sampling Plan Allocation',
        type: 'item',
        icon: 'material-outline:assignment_turned_in',
        url: '/samplingPlanAllocation',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.createResources',
        title: 'Create Resources',
        type: 'item',
        icon: 'feather:file-plus',
        url: '/createResources',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.learnerPortfolio',
        title: 'Learner Portfolio',
        type: 'item',
        icon: 'material-outline:folder_shared',
        url: '/learnerPortfolio',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.admin',
        title: 'Admin',
        type: 'item',
        icon: 'material-outline:admin_panel_settings',
        url: '/admin',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.courseBuilder',
        title: 'Course Builder',
        type: 'item',
        icon: 'material-outline:auto_stories',
        url: '/courseBuilder',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.allLearners',
        title: 'All Learners',
        type: 'item',
        icon: 'material-outline:groups',
        url: '/allLearners',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.forms',
        title: 'Forms',
        type: 'item',
        icon: 'material-outline:feed',
        url: '/forms',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.enrolments',
        title: 'Enrolments',
        type: 'item',
        icon: 'material-outline:person_add',
        url: '/enrolments',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.surverys',
        title: 'Surverys',
        type: 'item',
        icon: 'material-outline:ballot',
        url: '/surverys',
        auth : authRoles.admin,
      },
      {
        id: 'dashboards.communications',
        title: 'Communications',
        type: 'item',
        icon: 'heroicons-outline:chat-alt',
        url: '/communications',
        auth : authRoles.admin,
      }
];
export default navigationConfig;